### ISSUE TITLE
Wrong driver number generated by clrxdisasm for gfx900

### ISSUE THREAD

**Issue by zawawawa** [CLRX/CLRX-mirror#20]
clrxdisasm always sets .driver_version to 200406 by default. Since this version of the driver does not support Vega, clrxasm issues an error if the disassembled file for GCN5  codes is unmodified.

**Comment by matszpk** [comment]
A clrxdisasm have option '--driverVersion' or shorter '-t' to specify correct driver version number. I recommend to add this option while disassemblying and code for newer device than Hawaii/Bonaire. If you specify driver version 244208 or later, then code for a GFX900 will be correctly recognized (since this version driver support VEGA).

**Comment by matszpk** [comment]
Ok. I consider how to determine minimal driver version for particular GPU device type while disassemblying.

**Comment by matszpk** [comment]
Now, clrxdisasm can determine minimal driver version by GPU device type and supply correct version for GFX900 binaries.
