### ISSUE TITLE
A few basic questions

### ISSUE THREAD

**Issue by almson** [CLRX/CLRX-mirror#5]
First of all, thank you for making this available! The documentation alone is very helpful.

I recently started exploring the new ROCm platform (previously I worked in CUDA). As you're probably aware, ROCm has its own llvm-based GCN assembler. I would like to understand if a) this assembler supports creating HSACO objects that can be loaded by ROCm and b) what advantages it might have over llvm-mc. (llvm-mc is by no means perfect. Its status is "experimental." It is missing instructions and has no documentation to speak of.)

**Comment by matszpk** [comment]
Yes, I knew that ROCm have own disassembler, however I couldn't try ROCm because I was using incompatible Linux distro (opensuse). CLRX currently supports only AMDAPP OpenCL (1.x and 2.0) and GalliumCompute (no support for ROCm).
CLRadeonExtender give few features over llvm-mc: support below listed formats, advanced macro compliat with GNU as, alternate macro mode, better error messaging (much verbose than llvm-mc or GNU as), full support for GCN 1.0/1.1/1.2, simple configuration for supported formats, ...
Temporarily development of this project is suspended. Although, I have plans to return back to this project before end of this year.

**Comment by matszpk** [comment]
Good news. CLRadeonExtender supports ROCm binary format (HSACO). Ofcourse, syntax is differs from ROCm assembler (look up to ROCm binary format).
